#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=8192  # Requested Memory
#SBATCH -p gpu  # Partition
#SBATCH -G 1  # Number of GPUs
#SBATCH -t 1:00:00  # Job time limit
#SBATCH -o slurm-gputest.out  # %j = job ID



source /modules/apps/miniconda/22.11.1-1/etc/profile.d/conda.sh
conda activate tapsgm_gpu

nvidia-smi
python gpu_test.py