#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=8192  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 24:00:00  # Job time limit
#SBATCH -o slurm-ffjord2.out  # %j = job ID

module load miniconda
conda activate generativetmula 

python train_toy.py --data moons --dims 16-16-16 --layer_type concatsquash --save experiments/ffjord/moons16
python train_toy.py --data moons --dims 32-32-32 --layer_type concatsquash --save experiments/ffjord/moons32


python train_toy.py --data 8gaussians --dims 16-16-16 --layer_type concatsquash --save experiments/ffjord/8gaussians16
python train_toy.py --data 8gaussians --dims 32-32-32 --layer_type concatsquash --save experiments/ffjord/8gaussians32


python train_toy.py --data checkerboard --dims 16-16-16 --layer_type concatsquash --save experiments/ffjord/checkerboard16
python train_toy.py --data checkerboard --dims 32-32-32 --layer_type concatsquash --save experiments/ffjord/checkerboard32


python train_toy.py --data pinwheel --dims 16-16-16 --layer_type concatsquash --save experiments/ffjord/pinwheel16
python train_toy.py --data pinwheel --dims 32-32-32 --layer_type concatsquash --save experiments/ffjord/pinwheel32

