#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=8192  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 24:00:00  # Job time limit
#SBATCH -o slurm-checkerboard-ffjord-sgm.out  # %j = job ID

module load miniconda
conda activate generativetmula


python ffjord_sgm.py --data checkerboard --depth 1 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 3 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 5 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 7 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003

python ffjord_sgm.py --data checkerboard --depth 1 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 3 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 5 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 7 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003

python ffjord_sgm.py --data checkerboard --depth 1 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 3 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 5 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 7 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003

python ffjord_sgm.py --data checkerboard --depth 1 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 3 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 5 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 7 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003

python ffjord_sgm.py --data checkerboard --depth 1 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 3 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 5 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003
python ffjord_sgm.py --data checkerboard --depth 7 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003






python ffjord_sgm.py --data checkerboard --depth 1 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 3 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 5 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 64 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True

python ffjord_sgm.py --data checkerboard --depth 1 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 3 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 5 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 32 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True 

python ffjord_sgm.py --data checkerboard --depth 1 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 3 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 5 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 16 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True

python ffjord_sgm.py --data checkerboard --depth 1 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 3 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 5 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 8 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True

python ffjord_sgm.py --data checkerboard --depth 1 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 3 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True 
python ffjord_sgm.py --data checkerboard --depth 5 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 4 --tint 0.006 --finalT 0.3 --dt 0.0003 --rff True




