#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=8192  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 24:00:00  # Job time limit
#SBATCH -o slurm-ffjord-sgm.out  # %j = job ID

module load miniconda
conda activate generativetmula

python ffjord_sgm.py --data moons --depth 7 --dims 64 
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 64 
python ffjord_sgm.py --data checkerboard --depth 7 --dims 64 
python ffjord_sgm.py --data pinwheel --depth 7 --dims 64 
python ffjord_sgm.py --data 2spirals --depth 7 --dims 64 

python ffjord_sgm.py --data moons --depth 7 --dims 64 --rff True
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 64 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 64 --rff True
python ffjord_sgm.py --data pinwheel --depth 7 --dims 64 --rff True
python ffjord_sgm.py --data 2spirals --depth 7 --dims 64 --rff True


python ffjord_sgm.py --data moons --depth 7 --dims 32 
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 32 
python ffjord_sgm.py --data checkerboard --depth 7 --dims 32 
python ffjord_sgm.py --data pinwheel --depth 7 --dims 32 
python ffjord_sgm.py --data 2spirals --depth 7 --dims 32 

python ffjord_sgm.py --data moons --depth 7 --dims 32 --rff True
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 32 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 32 --rff True
python ffjord_sgm.py --data pinwheel --depth 7 --dims 32 --rff True
python ffjord_sgm.py --data 2spirals --depth 7 --dims 32 --rff True




python ffjord_sgm.py --data moons --depth 7 --dims 16 
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 16 
python ffjord_sgm.py --data checkerboard --depth 7 --dims 16 
python ffjord_sgm.py --data pinwheel --depth 7 --dims 16 
python ffjord_sgm.py --data 2spirals --depth 7 --dims 16 

python ffjord_sgm.py --data moons --depth 7 --dims 16 --rff True
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 16 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 16 --rff True
python ffjord_sgm.py --data pinwheel --depth 7 --dims 16 --rff True
python ffjord_sgm.py --data 2spirals --depth 7 --dims 16 --rff True



python ffjord_sgm.py --data moons --depth 7 --dims 8 
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 8 
python ffjord_sgm.py --data checkerboard --depth 7 --dims 8 
python ffjord_sgm.py --data pinwheel --depth 7 --dims 8 
python ffjord_sgm.py --data 2spirals --depth 7 --dims 8 

python ffjord_sgm.py --data moons --depth 7 --dims 8 --rff True
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 8 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 8 --rff True
python ffjord_sgm.py --data pinwheel --depth 7 --dims 8 --rff True
python ffjord_sgm.py --data 2spirals --depth 7 --dims 8 --rff True




python ffjord_sgm.py --data moons --depth 7 --dims 4
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 4 
python ffjord_sgm.py --data checkerboard --depth 7 --dims 4 
python ffjord_sgm.py --data pinwheel --depth 7 --dims 4
python ffjord_sgm.py --data 2spirals --depth 7 --dims 4 

python ffjord_sgm.py --data moons --depth 7 --dims 4 --rff True
python ffjord_sgm.py --data 8gaussians --depth 7 --dims 4 --rff True
python ffjord_sgm.py --data checkerboard --depth 7 --dims 4 --rff True
python ffjord_sgm.py --data pinwheel --depth 7 --dims 4 --rff True
python ffjord_sgm.py --data 2spirals --depth 7 --dims 4 --rff True