#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=8192  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 24:00:00  # Job time limit
#SBATCH -o slurm-ffjord.out  # %j = job ID

module load miniconda
conda activate generativetmula

python sgm_simple.py --data moons 
python sgm_simple.py --data 8gaussians 
python sgm_simple.py --data checkerboard 
python sgm_simple.py --data pinwheel 
python sgm_simple.py --data 2spirals 