#!/bin/bash
#SBATCH -c 8  # Number of Cores per Task
#SBATCH --mem=16384  # Requested Memory
#SBATCH -p cpu-long
#SBATCH -t 168:00:00  # Job time limit
#SBATCH -o ksd_tmula_ir.out  # %j = job ID

module load matlab/r2021a
matlab -r main_numerics


